[meta]
array_vars = "ALL"

[sbatch]
time = "1:00:00"
mem_per_cpu = "2000M"
gpu = false

[params]
backup_mode = "wm_partial"
forget_rate = [0.1, 0.2, 0.3, 0.4]
wm_decay = [0.3, 0.5, 0.7]
cost = [0.005, 0.01, 0.02]
seed = [1, 2]
beta_e_final = 0.01
num_envs = 64
num_updates = 30_000
network_type = "node_shared"
hidden_size = 64

use_q_values_obs = true
use_n_visits_obs = true
use_g_values_obs = true
use_time_elapsed_obs = true
use_recency_obs = false
use_best_open_value_obs = false
use_best_terminal_value_obs = false
use_is_terminal_obs = false

[[conditions]]
label = "basic"

[[conditions]]
label = "recency"
use_n_visits_obs = false
use_recency_obs = true

[[conditions]]
label = "terminal"
use_is_terminal_obs = true

[[conditions]]
label = "recency+terminal"
use_n_visits_obs = false
use_recency_obs = true
use_is_terminal_obs = true
