[meta]
array_vars = "ALL"

[sbatch]
time = "4:00:00"
mem_per_cpu = "2000M"
gpu = false

[params]
seed = [1,2]
beta_e_final = 0.001
cost = 0.005
forget_rate = [0.1, 0.2, 0.3, 0.4]
wm_decay = [0.3, 0.5, 0.7]

# basic: disable extra observations
use_recency_obs = false
