[meta]
array_vars = []

[sbatch]
time = "1:00:00"
gpu = true

[params]
cost = [0.001, 0.0025, 0.005, 0.01, 0.02, 0.04]
t_max = 100
beta_e_final = 0.005  # bumped
use_recency_obs = false  # perhaps reconsider

# # expensive training
# seed = [1, 2, 3, 4]
# num_envs = 128
# num_updates = 50_000

# cheap training
seed = [1,2]
num_envs = 64

wm_decay = 1.0
forget_rate = [0.05, 0.1, 0.2, 0.4]

activation_gates_backup_sink = false
activation_gates_backup_source = false
activation_masks_observation = false
activation_prevents_corruption = false  # this one matters
forget_discovered = true