[meta]
result_path = "./results"

[params]
seed = 15
network_type = "mlp"
hidden_size = 256
num_nodes = 15
beta_move = 40.0
eps_move = 0.0
learning_rate = 1.0
lamda_backup = 1.0
backup_steps = 100
wm_decay = 1.0
wm_backup = true
q_drop_rate = 0.0
q_drift = 0.0
q_decay = 1.0
t_max = 50
cost = 0.01
scale_factor = 0.125
shuffle_nodes = true
use_recency_obs = true
recency_decay = 0.5
mask_fixation = true
num_updates = 50000
num_envs = 256
rollout_length = 50
eval_episodes = 102400
lr = 0.0005
max_grad_norm = 2.0
gamma = 1.0
lamda = 0.8
beta_v = 0.05
beta_e_init = 0.02
beta_e_final = 0.001
print_frequency = 100
max_compiled_updates_per_chunk = -1
