# [meta]  # NOTE: previously train
# experiment = "hpgrid-dyna" # NOTE: default to file name without toml
# eval_episodes = 102400  # NOTE: add to arguments; 102400 is new default
# print_frequency = 100 # NOTE: same
# python = "python -u"
# entrypoint = "train_jax.py"
# result_path = "./results"
# resume = true
# jobid_from_task_id = true

[sbatch]
# job_name = "grid"  # NOTE: take from experiment if not provided
# cpus_per_task = 1
time = "04:00:00"
mem_per_cpu = "1G"
# error = "./log/%A_%a.err"
# output = "./log/%A_%a.out"

# [runtime]
# set_euo_pipefail = true
# force_jax_cpu = true
# threads_from_slurm = true

[params] # NOTE: previously grid
# environment
num_nodes = 15
t_max = 30
cost = 0.02
beta_move = 100.0
eps_move = 0.0
learning_rate = 1.0
wm_decay = 0.8
lamda_backup = 0.0
# network
hidden_size = 256
# training
seed = [1, 2, 3]
num_episodes = 16000000
batch_size = [64, 128]
# GAE
gamma = 1.0
lr = [0.0001, 0.0005, 0.001]
lamda = [0.9, 0.95]
# loss
beta_e_init = [0.05, 0.02]
beta_e_final = 0.0001
beta_v = 0.05
max_grad_norm = 2.0
