[params]
# fixed shape params
num_nodes = 15
hidden_size = 256
batch_size = 256
t_max = 50
num_episodes = 16_000_000
eval_episodes = 51200
recency_decay = [0, 0.5]

# env params
cost = [0.01, 0.02, 0.04]
beta_move = 100.0
eps_move = 0.0
learning_rate = 1.0
lamda_backup = 1.0
wm_decay = [0.5, 1.0]
shuffle_nodes = true
scale_factor = 0.125

# training params
seed = [1, 2, 3]
