[sbatch]
time = "8:00:00"
mem_per_cpu = "1000M"

[params]
# environment
num_nodes = 15
t_max = 50
cost = 0.01
beta_move = 100.0
eps_move = 0.0
learning_rate = 1.0
wm_decay = [0.5, 1.0]
backup_steps = [1, 8]
# network
hidden_size = 256
# training
seed = [1, 2, 3]
num_updates = 10_000
num_envs = 128
rollout_length = 50
# GAE
gamma = 1.0
lr = 0.001
lamda = 0.8
# loss
beta_e_init = 0.02
beta_e_final = 0.0001
beta_v = 0.05
max_grad_norm = 2.0
