[meta]

[environment]
num_nodes = 15
t_max = 50
wm_backup = true
wm_decay = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
cost = 0.01

[training]
beta_e_final = 0.0001
max_grad_norm = 2.0
num_updates = 50000
num_envs = 128
rollout_length = 50
seed = [1, 2, 3]

[network]
hidden_size = 256

[sbatch]
time = "8:00:00"
mem_per_cpu = "1000M"
