[sbatch]
time = "8:00:00"
mem_per_cpu = "1000M"

[params]
# environment
num_nodes = 15
t_max = 50
cost = 0.01
wm_decay = [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
wm_backup = true
# network
hidden_size = 256
# training
seed = [1, 2, 3]
num_updates = 50_000
num_envs = 128
rollout_length = 50
# loss
beta_e_final = 0.0001
max_grad_norm = 2.0
